### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by nutcracker89** [CodingByHarry/scum_log_parser_os#1]
Hi 
wanted to try out your code but got this error when running it on Windows 10.
Folders and files have full permission seems like it can't rename file when it is open in ruby  

```
=== [2021-11-26 17:04:07 +0000] Parse Chat Files ===================
Parsing logs/chat_20211123171652.log
{ 820 rufus-scheduler intercepted an error:
  820   job:
  820     Rufus::Scheduler::EveryJob "1m" {}
  820     ["run_chats.rb", 11]
  820   error:
  820     820
  820     Errno::EACCES
  820     Permission denied @ rb_file_s_rename - (logs/chat_20211123171652.log, /logs/_processed/chat_20211123171652.log)
```

Regards Johnny

**Comment by CodingByHarry** [comment]
I didn't try this on windows and honestly not sure I'd bother trying to get it working.

I'd grab VirtualBox and install CentOS or grab a cheap VPS and chuck Centos on it.
[I use Quantum Core](https://quantumcore.com.au/clients/cart.php?a=confproduct&i=0) which works out to be around $3.50usd per month. Very cheap :)
