### ISSUE TITLE
SFTP

### ISSUE THREAD

**Issue by KumariAshamaki** [CodingByHarry/scum_log_parser_os#4]
My host just switched over to using SFTP I tried to convert it but only got so far. Any Ideas on how I could convert fetch_files.rb from net-ftp over to net-sftp? If not no worries just thought I would ask.

**Comment by CodingByHarry** [comment]
Wow, you're still using the bot 😂 It shouldn't be too hard to convert this to use SFTP. This article covers quite a lot --  https://sftptogo.com/blog/rails-sftp/

Feel free to open a PR if you fix this and I can merge it in. But also understandable if you'd rather keep to yourself! 👍

**Comment by KumariAshamaki** [comment]
XD Yeah I mainly use the prisoner bot as its free for me on GGHost and frees up time for me to work on other things but I wanted to get back into this one for some more custom stuff and automation. Was perfect until GGHost switched over to SFTP XD

**Comment by KumariAshamaki** [comment]
I have most of it figured out but not sure how to convert this part "entry = Net::FTP::List.parse(entry)" trying to figure out what the equivalent is. Still a code noob XD and yeah I will do a pull but I would recommend for the new version for SFTP to be a separate file that is optional as some host still use FTP and I have not the slightest idea of how to make it use both let alone detect what should be used XD

**Comment by KumariAshamaki** [comment]
`
# frozen_string_literal: true

require "fileutils"
require "net/sftp"
require "net/ftp/list"

class FetchFiles
  FTP_HOST = ""
  FTP_PORT = 
  FTP_USERNAME = ""
  FTP_PASSWORD = ""
  FTP_BASE_PATH = ""

  attr_reader :type

  def initialize(type:)
    @type = type
  end

  def execute!
    FileUtils.rm_rf Dir.glob("logs/#{type}_*.log")

    ftp = Net::SFTP.start('IP', 'USR', :password => 'PASS', :port => '0000')

    ftp.dir.foreach("/DIR/") do |entry|
    #ftp.list(FTP_BASE_PATH) do |list_entry|
      entry = Net::FTP::List.parse(entry)

      next unless entry.file?
      next unless entry.basename.start_with?("#{type}_")

      if !File.exists?("logs/_processed/#{entry.basename}")
        ftp.getbinaryfile("#{FTP_BASE_PATH}/#{entry.basename}", "logs/#{entry.basename}")
        puts "Downloaded #{entry.basename}"
      end
    end

    ftp.close

    puts "Ready!"
  end
end
`
Just gotten about this far. I know some of what I have done is jank af but ayo its getting there XD

**Comment by KumariAshamaki** [comment]
XD Yeah I mainly use the prisoner bot as it's free for me on GGHost and frees up time for me to work on other things but I wanted to get back into this one for some more custom stuff and automation. Was perfect until GGHost switched over to SFTP.
I have most of it figured out but not sure how to convert this part.
`entry = Net::FTP::List.parse(entry)`
Trying to figure out what the equivalent is. Still a code noob XD and yeah I will do a pull but I would recommend for the new version for SFTP to be a separate file that is optional as some host still use FTP and I have not the slightest idea of how to make it use both let alone detect what should be used XD. To be honest I think my biggest issue with the `entry = Net::FTP::List.parse(entry)` as I am not 100% sure what it is even doing XD. It's like solving a mystery its fun but my lack of knowledge makes it a massive challenge sometimes the worst part is knowing its simple XD.

```
# frozen_string_literal: true

require "fileutils"
require "net/sftp"
require "net/ftp/list"

class FetchFiles
  FTP_HOST = ""
  FTP_PORT = 
  FTP_USERNAME = ""
  FTP_PASSWORD = ""
  FTP_BASE_PATH = ""

  attr_reader :type

  def initialize(type:)
    @type = type
  end

  def execute!
    FileUtils.rm_rf Dir.glob("logs/#{type}_*.log")

    ftp = Net::SFTP.start(FTP_HOST, FTP_USERNAME, :password => FTP_PASSWORD, :port => FTP_PORT)

    ftp.dir.foreach("/DIR/") do |entry|
    #ftp.list(FTP_BASE_PATH) do |list_entry|
      entry = Net::FTP::List.parse(entry)

      next unless entry.file?
      next unless entry.basename.start_with?("#{type}_")

      if !File.exists?("logs/_processed/#{entry.basename}")
        ftp.getbinaryfile("#{FTP_BASE_PATH}/#{entry.basename}", "logs/#{entry.basename}")
        puts "Downloaded #{entry.basename}"
      end
    end

    ftp.close

    puts "Ready!"
  end
end
```

Just gotten about this far. I know some of what I have done is jank af but ayo its getting there XD. GGHost also does not seem to take URIs no matter what I do. Only way I have been able to connect and list files as a test was this.
```
require 'net/sftp'

Net::SFTP.start('IP', 'USR', :password => 'PASS', :port => '8822') do |sftp|

  # list the entries in a directory
  sftp.dir.foreach("/SaveFiles/Logs") do |entry|
    puts entry.longname
  end
end

```
If I try the same method in your script it gives an unexpected end.

**Comment by KumariAshamaki** [comment]
My dumb ass had to remove the comment and re-do it because I leaked my info and it showed in the edits oops! XD

**Comment by KumariAshamaki** [comment]
Dog I shit you not I asked my community if anyone could help and dude said "Use ChatGPT" I was like hmm maybe and the sum bitch figured it out! XD

```
# frozen_string_literal: true

require "fileutils"
require "net/sftp"
require "net/ftp/list"

class FetchFiles
  SFTP_HOST = "64.185.227.82"
  SFTP_PORT = 8822
  SFTP_USERNAME = "codil"
  SFTP_PASSWORD = "YIB1A2"
  SFTP_BASE_PATH = "/64.185.227.82_7002/SaveFiles/Logs"

  attr_reader :type

  def initialize(type:)
    @type = type
  end

  def execute!
    FileUtils.rm_rf Dir.glob("logs/#{type}_*.log")

    Net::SFTP.start(SFTP_HOST, SFTP_USERNAME, password: SFTP_PASSWORD, port: SFTP_PORT) do |sftp|
      sftp.dir.foreach(SFTP_BASE_PATH) do |entry|
        next unless entry.file?
        next unless entry.name.start_with?("#{type}_")

        if !File.exists?("logs/_processed/#{entry.name}")
          sftp.download("#{SFTP_BASE_PATH}/#{entry.name}", "logs/#{entry.name}")
          puts "Downloaded #{entry.name}"
        end
      end
    end

    puts ""
  end
end
```

**Comment by KumariAshamaki** [comment]
Dog I shit you not I asked my community if anyone could help someone said "Dude ask Chat GPT" and the sum bitch got it XD!
```
# frozen_string_literal: true

require "fileutils"
require "net/sftp"
require "net/ftp/list"

class FetchFiles
  SFTP_HOST = ""
  SFTP_PORT = 
  SFTP_USERNAME = ""
  SFTP_PASSWORD = ""
  SFTP_BASE_PATH = ""

  attr_reader :type

  def initialize(type:)
    @type = type
  end

  def execute!
    FileUtils.rm_rf Dir.glob("logs/#{type}_*.log")

    Net::SFTP.start(SFTP_HOST, SFTP_USERNAME, password: SFTP_PASSWORD, port: SFTP_PORT) do |sftp|
      sftp.dir.foreach(SFTP_BASE_PATH) do |entry|
        next unless entry.file?
        next unless entry.name.start_with?("#{type}_")

        if !File.exists?("logs/_processed/#{entry.name}")
          sftp.download("#{SFTP_BASE_PATH}/#{entry.name}", "logs/#{entry.name}")
          puts "Downloaded #{entry.name}"
        end
      end
    end

    puts ""
  end
end
```

**Comment by CodingByHarry** [comment]
Nice :) Glad to hear you got it working.
